// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNDqERLnuwaK7DkXXXFPGJBHx3nsfUP8',
    appId: '1:391875349362:android:09e49518f53b7be147abeb',
    messagingSenderId: '391875349362',
    projectId: 'planit-636a0',
    storageBucket: 'planit-636a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqN-AStOFWsdOoClHgUa1f0vABP1c5U0',
    appId: '1:391875349362:ios:d071d0d854d273f547abeb',
    messagingSenderId: '391875349362',
    projectId: 'planit-636a0',
    storageBucket: 'planit-636a0.firebasestorage.app',
    androidClientId: '391875349362-kqbjs5qckvvqu0pgmpj7na1auagp9i67.apps.googleusercontent.com',
    iosClientId: '391875349362-1gqihi2kj5aquico8n7i44iqkps0ia6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.planit',
  );

}